### ISSUE TITLE
[Feature] improvements for http

### ISSUE THREAD

**Issue by erlendoyen** [ThomasVon2021/blikvm#131] opened 2024-01-15 18:25 UTC
-add https support
-add rewrite or some kind of proxying for the backend client port for console redirection, so that you only have to expose the https port in the frontend.

testing now with nginx to work around it, have not managed to get the remote console to work, it's as if the reference to remote console i set, and is not translated/dynamic , if https://blikvmip/video could be used as part of the url for example we could have a directive nginx to then connect to 8008 in the backend.

**Comment by owendelong** [comment] 2024-01-17 03:03
IMHO, this should be closed as a duplicate of #41

**Comment by ThomasVon2021** [comment] 2024-09-19 08:39
https://wiki.blicube.com/blikvm/en/https/

You can update to v1.4.5 to test. If you have any problem, you can open the issue again.

**Closed** 2024-09-19 08:39 UTC
Labels: feature, BliKVM Matrix release

**Comment by erlendoyen** [comment] 2024-09-19 16:37
yes, already tested, thanks.
