### ISSUE TITLE
No web interface on Blikvm v4

### ISSUE THREAD

**Issue by singspeal1** [ThomasVon2021/blikvm#177] opened 2024-08-06 03:57 UTC
Hi Support,

I can ping the device but when I put ip address on google chrome. It doesn't show up anything. 

Tks
Kevin

**Comment by ThomasVon2021** [comment] 2024-08-06 04:08
use http not https

**Comment by singspeal1** [comment] 2024-08-06 04:12
I am not using https. Even I can't telnet ipaddress:80 but I can telnet ipaddress:8008

**Comment by ThomasVon2021** [comment] 2024-08-06 04:16
Can you use console port to debug
https://wiki.blicube.com/blikvm/en/BliKVM-v4-guide/#serial-console-access-via-the-5v-port
```
ps -aux | grep link
```
kvm-link is the web soft.

**Comment by singspeal1** [comment] 2024-08-06 04:20
I can use putty to  access the device.

**Comment by singspeal1** [comment] 2024-08-06 04:29
![Capture](https://github.com/user-attachments/assets/6a0b2651-d6a2-4c3f-ac29-bc9b8b9921f2)

**Comment by singspeal1** [comment] 2024-08-06 04:32
![Capture](https://github.com/user-attachments/assets/ec0e27b6-f415-4e06-a875-ed04d03c54b2)

**Comment by singspeal1** [comment] 2024-08-06 04:35
> Can you use console port to debug https://wiki.blicube.com/blikvm/en/BliKVM-v4-guide/#serial-console-access-via-the-5v-port
> 
> ```
> ps -aux | grep link
> ```
> 
> kvm-link is the web soft.

sorry I quite dont' get your point. Please advice

**Comment by ThomasVon2021** [comment] 2024-08-06 06:04
```
systemctl status kvmd-web
```

**Comment by ThomasVon2021** [comment] 2024-08-06 06:07
https://github.com/ThomasVon2021/blikvm/tree/master/package/kvmd-web

kvm-link is the web process，If this program doesn't start, it definitely won't be able to open the website. First, check the status to see if you can find the reason for the startup failure. I think flashing the system should be able to restore it.

**Comment by singspeal1** [comment] 2024-08-06 06:22
![Capture](https://github.com/user-attachments/assets/61a42318-ee10-4053-bed1-d8963218bbb1)

**Comment by singspeal1** [comment] 2024-08-06 06:23
Please instruct me how to restore it

**Comment by ThomasVon2021** [comment] 2024-08-06 06:37
https://wiki.blicube.com/blikvm/en/flashing_os/

**Comment by singspeal1** [comment] 2024-08-06 06:57
do u have video to guide to do it step by step. I dont' feel comfortable to do it without very clear guideline
BTW, how can I do 1 to 1 replacement?

**Comment by ThomasVon2021** [comment] 2024-08-06 07:00
There is no video, the problem is very clear. The kvm-link is damaged. You can skip flashing the system and download the latest package of kvm link from GitHub release. Then replace the kvm link program under/usr/bin/blikvm, and restart it to restore normal operation.
https://github.com/ThomasVon2021/blikvm/releases

**Comment by ThomasVon2021** [comment] 2024-08-06 07:04
There should be no problem with the hardware, just replace the software. Please don't worry too much. If it is not fixed in the end, you can return it for a replacement. Please feel free to try it out.

**Comment by ThomasVon2021** [comment] 2024-08-06 07:05
or you can join discord, uncertain steps can be communicated in a timely manner

**Comment by singspeal1** [comment] 2024-08-06 08:25
![Capture](https://github.com/user-attachments/assets/a462fc5b-0c16-45d1-acc1-d73511d475c3)
which version that I need to download

**Comment by ThomasVon2021** [comment] 2024-08-06 08:31
Can you join Discord? I can send it directly to you in discord, but communication here is too slow.
the release-h616-v4.tar.gz, 
After decompression, there is a kvm-link program inside, just replace it with kvm-ink in/usr/bin/blikvm.

**Comment by singspeal1** [comment] 2024-08-06 08:33
I joned Discord. My user name is singspeal1

**Closed** 2024-08-12 01:32 UTC
